"""watchlists table

Revision ID: 47d18612fbd1
Revises: b1522cd85b0b
Create Date: 2021-02-03 21:03:38.945914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d18612fbd1'
down_revision = 'b1522cd85b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('price', sa.Float(precision=16), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index(op.f('ix_stock_currency'), 'stock', ['currency'], unique=True)
    op.create_index(op.f('ix_stock_price'), 'stock', ['price'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_name'), 'watchlist', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_name'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_stock_price'), table_name='stock')
    op.drop_index(op.f('ix_stock_currency'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
