"""stocks table

Revision ID: 4f3de7f808c9
Revises: 47d18612fbd1
Create Date: 2021-02-03 21:08:29.113811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3de7f808c9'
down_revision = '47d18612fbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_ticker'), 'stock', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_ticker'), table_name='stock')
    # ### end Alembic commands ###
