"""stocks table

Revision ID: 836d217c00d3
Revises: 4f3de7f808c9
Create Date: 2021-02-03 23:31:18.147180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836d217c00d3'
down_revision = '4f3de7f808c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_currency', table_name='stock')
    op.create_index(op.f('ix_stock_currency'), 'stock', ['currency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_currency'), table_name='stock')
    op.create_index('ix_stock_currency', 'stock', ['currency'], unique=1)
    # ### end Alembic commands ###
